version: '3.7'
services:
  countries-service-qa:
    build:
      context: ..
      dockerfile: local/Dockerfile
    container_name: countries-service-qa
    environment:
      SPRING_PROFILES: qa
    ports:
      - "8080:8080"
    depends_on:
      - countries-data-wiremock-api

  countries-data-wiremock-api:
    image: rodolpheche/wiremock:2.31.0
    container_name: countries-data-wiremock-api
    volumes:
      - ../wiremock/__files:/home/wiremock/__files
      - ../wiremock/mappings:/home/wiremock/mappings
    ports:
      - "9000:8080"

  countries-service-dev:
    build:
      context: ..
      dockerfile: local/Dockerfile
    container_name: countries-service-dev
    environment:
      SPRING_PROFILES: dev
    ports:
      - "8081:8080"
    depends_on:
      - countries-data-wiremock-api
