server:
  shutdown: graceful
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: NEVER
    include-exception: false

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

feature:
  countries-v1: false
  countries-service: false
