apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: countries-service

build:
  local:
    push: false
    concurrency: 0
  tagPolicy:
    gitCommit:
      variant: CommitSha
      ignoreChanges: true
  artifacts:
    - image: countries-service/countries-service-api
      context: countries-service-assembly
      docker:
        buildArgs:
          JAR_FILE: ./build/libs/countries-service-assembly-latest.jar
          INFO_APP_BUILD: "{{ .BUILD_ID }}"
